// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmCBG7pDMLcLlyvdmB0IbbQ7ZQMOdOgo',
    appId: '1:385900976442:web:63b7c977fb13f3fdaf5803',
    messagingSenderId: '385900976442',
    projectId: 'boardgame-pp',
    authDomain: 'boardgame-pp.firebaseapp.com',
    storageBucket: 'boardgame-pp.appspot.com',
    measurementId: 'G-WBS40YJBS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0CpAAha-7cttCEuzFP848Ku_dtJ8Fquw',
    appId: '1:385900976442:android:8dc5236ef32aff76af5803',
    messagingSenderId: '385900976442',
    projectId: 'boardgame-pp',
    storageBucket: 'boardgame-pp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkZQbjbjSdX25k-qp41943zq_IqtFG31s',
    appId: '1:385900976442:ios:89dcb3e8cf51fb9eaf5803',
    messagingSenderId: '385900976442',
    projectId: 'boardgame-pp',
    storageBucket: 'boardgame-pp.appspot.com',
    iosClientId: '385900976442-m7rvujals31a4ogtg9fqkq8ppmi08cj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.boardgameAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkZQbjbjSdX25k-qp41943zq_IqtFG31s',
    appId: '1:385900976442:ios:89dcb3e8cf51fb9eaf5803',
    messagingSenderId: '385900976442',
    projectId: 'boardgame-pp',
    storageBucket: 'boardgame-pp.appspot.com',
    iosClientId: '385900976442-m7rvujals31a4ogtg9fqkq8ppmi08cj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.boardgameAppFlutter',
  );
}
